export const SITE = {
  name: "Asmato Laundry and Cleaning Services",
  shortName: "ASMATO",
  tagline: "Laundry & Cleaning Services",
  phone: "+234 803 123 4567",
  phoneHref: "tel:+2348031234567",
  whatsappNumber: "2348031234567",
  email: "hello@asmatocleaning.com",
  address: "Ogbomoso, Oyo State, Nigeria",
  hoursWeek: "Mon–Sat: 7:00 AM – 7:00 PM",
  hoursSun: "Sunday: 9:00 AM – 5:00 PM  •  Emergency 24/7",
};

export const whatsappUrl = (message: string) =>
  `https://wa.me/${SITE.whatsappNumber}?text=${encodeURIComponent(message)}`;

export const SERVICES = [
  {
    slug: "commercial",
    icon: "🏢",
    name: "Commercial Cleaning",
    short: "Office blocks, retail stores, banks, schools, and commercial spaces — cleaned to the highest standard.",
    badges: ["Office", "Retail", "Schools"],
    included: [
      "Office deep cleaning",
      "Floor mopping & polishing",
      "Restroom sanitization",
      "Waste disposal",
      "Reception & common areas",
    ],
    idealFor: "Offices, banks, schools, shops, churches",
    equipment: ["Industrial mops", "Vacuums", "Sanitizing sprayers"],
    image: "commercial",
  },
  {
    slug: "industrial",
    icon: "🏭",
    name: "Industrial Cleaning",
    short: "Factories, warehouses, production floors, and heavy industrial facilities requiring specialist equipment.",
    badges: ["Heavy Duty", "Machinery", "Warehouse"],
    included: [
      "Factory floor scrubbing",
      "Machinery exterior cleaning",
      "Warehouse deep clean",
      "Pressure washing",
      "Hazardous waste handling",
    ],
    idealFor: "Factories, production plants, warehouses",
    equipment: ["Pressure washers", "Industrial scrubbers", "PPE"],
    image: "industrial",
  },
  {
    slug: "window",
    icon: "🪟",
    name: "Window Cleaning",
    short: "Internal and external window cleaning for residential and commercial buildings — streak-free, crystal clear.",
    badges: ["Residential", "High-Rise", "Streak-Free"],
    included: [
      "Internal window cleaning",
      "External window cleaning",
      "Frame and sill cleaning",
      "High-rise window access",
      "Streak-free guarantee",
    ],
    idealFor: "Homes, offices, hotels, high-rise buildings",
    equipment: ["Water-fed poles", "Squeegees", "Extension ladders"],
    image: "window",
  },
  {
    slug: "upholstery",
    icon: "🛋️",
    name: "Upholstery Cleaning",
    short: "Deep cleaning of sofas, chairs, mattresses, carpets, and fabric surfaces — removing stains, dust, and allergens.",
    badges: ["Sofa", "Mattress", "Carpet"],
    included: [
      "Sofa & chair deep cleaning",
      "Mattress sanitization",
      "Carpet & rug cleaning",
      "Stain removal treatment",
      "Deodorizing & freshening",
    ],
    idealFor: "Homes, hotels, offices, churches",
    equipment: ["Steam cleaners", "Extraction machines", "Stain treatment products"],
    image: "upholstery",
  },
  {
    slug: "domestic",
    icon: "🏠",
    name: "Domestic Cleaning",
    short: "Full home cleaning services — kitchen, bathrooms, bedrooms, and living areas cleaned professionally inside and out.",
    badges: ["Deep Clean", "Regular", "Move-In/Out"],
    included: [
      "Full kitchen deep clean",
      "Bathroom & toilet sanitization",
      "Bedroom & living room",
      "Move-in/move-out cleaning",
      "Post-construction cleaning",
    ],
    idealFor: "Homes, apartments, rental properties",
    equipment: ["Eco-friendly products", "Steam mops", "HEPA vacuums"],
    image: "domestic",
  },
  {
    slug: "fumigation",
    icon: "🪲",
    name: "Fumigation",
    short: "Licensed pest control and fumigation for homes, offices, warehouses, and farms — eliminating termites, cockroaches, rodents, and all pests.",
    badges: ["Licensed", "All Pests", "Residential & Commercial"],
    included: [
      "Termite treatment",
      "Cockroach elimination",
      "Rodent control",
      "Mosquito & bedbugs treatment",
      "Farm & warehouse fumigation",
    ],
    idealFor: "Homes, offices, warehouses, farms, restaurants",
    equipment: ["Licensed chemicals", "ULV foggers", "Full PPE"],
    image: "fumigation",
  },
] as const;

export type Service = (typeof SERVICES)[number];
